# geany use both C and C++, so advertize C++
language: cpp
dist: trusty
sudo: required
compiler:
  - gcc

git:
  quiet: true

addons:
  apt:
    packages:
      - intltool
      - libtool
      - libgtk-3-dev
      - python-docutils
      - rst2pdf
      - python-lxml
 
#install:
  # try not to install doxygen-latex because we don't need it and it's huge
  #- sudo apt-get install -y --no-install-recommends doxygen

before_script:
  #- export CFLAGS="-g -O2 -Werror=pointer-arith -Werror=implicit-function-declaration"
  - URL=$(wget --quiet "http://download.geany.org/" -O - | grep -e "geany-.*\.tar\.gz<" | tail -n 1 | cut -d '"' -f 2)
  - export VERSION=$(echo "$URL" | sed -r 's/.*geany-(.*).tar.gz/\1/')
  - wget -c "http://download.geany.org/$URL"
  - tar xvf "geany-${APP_VERSION}.tar.gz"

script:
  - ./configure --enable-gtk3=yes --enable-binreloc
  - make -j$(nproc)
  - make -j$(nproc) check
  - make install

#after_success:
#  - >
#    wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
#    bash upload.sh geany-"$ARCH".AppImage*

#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
