# geany use both C and C++, so advertize C++
language: cpp
dist: xenial
sudo: required
compiler:
  - gcc

git:
  quiet: true

addons:
  apt:
    packages:
      - patchelf
      - librsvg2-dev
      - intltool
      - libtool
      - python-docutils
      - python-lxml
      - libgtk-3-dev
 
before_script:
  - export APP=Geany
  - export LOWERAPP=${APP,,}
  - export APPDIR="$(pwd)/appdir" ; mkdir --parents ${APPDIR} ; find ${APPDIR}

script:
  - bash ./make_geany.sh

after_success:
  - find ${APPDIR} -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file Geany*.AppImage https://transfer.sh/Geany-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Geany*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
