name: AppImage Build
on:
  release:
    types: [created, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  build:
    #ubuntu bionic:
    runs-on: ubuntu-18.04
  
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
  
    # Runs a single command using the runners shell
    - name: Install required dependencies
      run: sudo apt-get install --yes wget subversion patchelf librsvg2-dev intltool libtool python-docutils python-lxml libgtk-3-dev
  
    # Runs a set of commands using the runners shell
    - name: Executing AppImage build
      run: bash ./make_geany.sh
  
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: ${{ github.event.inputs.tag }}
        name: "Release build (${{ github.event.inputs.tag }})"
        artifacts: "Geany*.AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}
